### ISSUE TITLE
Alternative usage with all mint commands

### ISSUE THREAD

**Issue by Namek** [mint-lang/mint-docker#1]
## Prepare

Create such `Dockerfile`:

```Dockerfile
FROM alpine:latest

# you may want to change URL to https://mint-lang.s3-eu-west-1.amazonaws.com/mint-latest-linux if want pre-release version
RUN wget -O mint https://github.com/mint-lang/mint/releases/download/0.7.1/mint-0.7.1-linux
RUN chmod +x mint

EXPOSE 3000
WORKDIR /proj
ENTRYPOINT ["/mint"]
```

Then invoke this command from the path where `Dockerfile` is installed, to build the docker image:

`docker build -t mint .`

## Basic usage

To invoke just the basic `mint` command do it like this:
```
docker run --tty -v c:/dev/Projects/my_project:/proj -p 3000:3000 --rm -ti mint
```

It maps the `c:/dev/Projects/my_project` directory to container-local working directory (called `proj`) for `mint`.

Append to this command anything that's going to be a parameter for `mint` command.

## Working on a project

Init project called `my_project` in directory `c:/dev/Projects` which will create a folder `my_project`:
```
docker run --tty -v c:/dev/Projects:/proj mint init my_project
```

To run `mint start` from the project directory `c:/dev/Projects/my_project` invoke:

```
docker run --tty -v c:/dev/Projects/my_project:/proj -p 3000:3000 --rm -ti mint start -h 0.0.0.0
```

then open http://localhost:3000

## Running on Windows

On Windows you may want to use this batch file `mint_start.bat` by invoking directly from project's directory: 

```batch
@echo off
echo Run this batch from project's directory!
docker run --tty -v "%cd%":/proj -p 3000:3000 --rm -ti mint start -h 0.0.0.0
```
then open http://localhost:3000

and `mint_test.bat`:
```batch
@echo off
echo Run this batch from project's directory!
docker run --tty -v "%cd%":/proj -p 3001:3001 --rm -ti mint test --manual --host 0.0.0.0
```
then open http://localhost:3001

**Comment by gdotdesign** [comment]
This is great! I think we an use this as an official Mint docker image, I'll update the one I have in Docker Hub https://hub.docker.com/repository/docker/mintlang/mint

**Comment by gdotdesign** [comment]
I've updated the readme with commands including plain Docker.
