### ISSUE TITLE
Mint base image on DockerHub

### ISSUE THREAD

**Issue by ryanprior** [mint-lang/mint-docker#4]
Hey again! This is a follow-up to #3. It would be nice to have an image people can pull from DockerHub to use Mint in their workflows. We could create an organization there called `mint-lang` and push the image from #3 as `mint-lang/mint` or similar.

We could then offer an alternate way to install in Docker on https://www.mint-lang.com/install ­like so:

```sh-session
$ docker pull mint-lang/mint
$ docker run --rm -it -v $PWD:/opt/mint ming-lang/mint init hello-mint
```

**Comment by ryanprior** [comment]
And to be clear, when I say "we" I mean I am volunteering to do this work or support somebody else on the Mint team in doing it. Let me know any way I can help =D

**Comment by gdotdesign** [comment]
>  It would be nice to have an image people can pull from DockerHub to use Mint in their workflows. We could create an organization there called `mint-lang` and push the image from #3 as `mint-lang/mint` or similar.

We have DockerHub repository already https://hub.docker.com/orgs/mintlang and a repository https://hub.docker.com/repository/docker/mintlang/mint, it's just not updated.

> And to be clear, when I say "we" I mean I am volunteering to do this work or support somebody else on the Mint team in doing it. Let me know any way I can help =D

It would be awesome if you could integrate pushing the docker image into the workflows we have already 
https://github.com/mint-lang/mint/tree/master/.github/workflows (probably the linux ones), let me know what you need to do that :)

-----

Related issues and prs: #1 #2

**Comment by ryanprior** [comment]
Ah, I searched for "mint" but it doesn't show your image in the first 5 pages! I'll test a workflow using my own repo and then make a PR to `mint-lang/mint` for your review.

A couple Qs:

### Where does the Dockerfile live?

Do you prefer that the Mint Dockerfile should live in the `mint` repo or is it better here as per #3? Keeping it over there has the advantage of avoiding creating a cross-repo dependency, while keeping it here maybe separates concerns better if you don't want Docker-related stuff in the main repo.

### How do we structure releases?

The easiest thing to do is to build an image on every push to `master` and push that to DockerHub as `latest`. But if you want to allow users to use a specific Mint release then we also want to push version-specific tags, and if we want to do a stable release that's another tag, and of course we can get as fancy as we want with this.

So my proposal to start is that we don't do any of that until later, we get the basic "push master as latest" workflow set up and then create further issues to track the more sophisticated release strategy we might want in the future.

**Comment by gdotdesign** [comment]
> Where does the Dockerfile live?

It can live in the main repo, there is already `docker-compose.yml` to build the release binaries.

> How do we structure releases?

We already have latest binaries which is built every time something is pushed to `master`, also we have versioned binaries which are built when a new version tag is created. 

So I think having a `latest` from `master` and version from the tags will be enough for now.

**Comment by Namek** [comment]
@ryanprior are you working on this?

**Comment by gdotdesign** [comment]
I've set up automated builds to Mint here https://hub.docker.com/repository/docker/mintlang/mint, it builds `master` as `latest` and tags as themselves.

**Comment by ryanprior** [comment]
@gdotdesign this is nice, thank you!
